# docker build -t mobz/elasticsearch-head:5-alpine -f Dockerfile-alpine .

FROM node:alpine
RUN npm install -g grunt
RUN npm install -g grunt-cli
RUN npm install    grunt grunt-http-server
WORKDIR /usr/src/app
RUN mv /node_modules .
COPY . .
EXPOSE 9100
CMD grunt --gruntfile Gruntfile-alpine.js http-server:dev
